### ISSUE TITLE
Name clash issue

### ISSUE THREAD

**Issue by ilg-ul** [SeyyedKhandon/zpack#1]
Hi, I stumbled by chance upon your VSCode extension `seyyedkhandon.xpack`.

Please note that the name **xPack** is already in use by [The xPack Project](https://github.com/xpack), with lots of repositories:

- https://github.com/xpack
- https://github.com/xpack-dev-tools
- https://github.com/xpack-3rd-party
- https://github.com/micro-os-plus

Using it for a different project, even with a slightly adjusted spelling, is highly unfortunate, since it'll lead to confusion.

Unless you decide to contribute to **The xPack project**, I would appreciate you choosing a better name for your repo and extension (that does not come up when searching for `xpack`), and unpublishing `seyyedkhandon.xpack` form the VSCode marketplace.

Thank you for your understanding,

Liviu

**Comment by SeyyedKhandon** [comment]
### First I should note that I changed the name to `zpack`, but I should tell you to consider this:

As you can see when a user searches `xpack` , he/she will see two totally different extensions which can not be confused with another one(title and logos are totally different). 
![image](https://user-images.githubusercontent.com/59599950/117289840-5598f080-ae82-11eb-806b-25bfb5bed805.png)
And the reason which I took that name, as you can see, was that I'm was intended to make an ext-pack series which the x one has all of them.
![image](https://user-images.githubusercontent.com/59599950/117290171-b7f1f100-ae82-11eb-9fb8-064f1617dd04.png)
So, I think your request is not reasonable enough for anyone to change their selected names until you tell that you took the trademark for this name.

have a good time😉

**Comment by ilg-ul** [comment]
Thank you!
